name: goplay
description: goplay

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  animated_splash_screen: ^1.1.0
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/splash_screen/goplay_icon.svg
    - assets/images/splash_screen/goplay_title_image.svg
    - assets/images/game_selection/glasses.svg
    - assets/images/game_selection/button_start_game.svg
    - assets/images/game_mode/radio_selected.svg
    - assets/images/game_mode/radio_unselected.svg
    - assets/images/icons/clear.svg
